# Launch bot
name: sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: bot-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-24.04
    env:
      INPUT_READ_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_WRITE_TOKEN: ${{ secrets.PODMAN_DESKTOP_BOT_TOKEN }}
      INPUT_SLACK_URL: ${{ secrets.SLACK_URL }}
      INPUT_SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Keep workflow alive
      run: |
        git config --global user.email "bot@podman-desktop.io"
        git config --global user.name "Podman Desktop Bot"
        git clone --branch info https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/benoitf/podman-desktop-bot.git /tmp/podman-desktop-bot-info
        cd /tmp/podman-desktop-bot-info
        date --iso-8601=seconds > last-run.txt
        git add last-run.txt
        git commit -m "Keep workflow alive" || true
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/benoitf/podman-desktop-bot.git" info || true
    - name: Execute pnpm
      run: pnpm install --frozen-lockfile
    - name: synchronize
      run: |
        pnpm install
        pnpm run compile
        node dist/entrypoint.js
