# Launch bot
name: sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    env:
      INPUT_READ_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_WRITE_TOKEN: ${{ secrets.PODMAN_DESKTOP_BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: synchronize
      run: |
        yarn
        yarn run compile
        node dist/entrypoint.js
